### ISSUE TITLE
problem with python-novaclient (4.0.0)

### ISSUE THREAD

**Issue by chongk-t** [ibmcb/cbtool#108]
cb --hard_reset end up with the error " _**'VolumeManager' object has no attribute 'list'**_ "
novaclient v2 provides a different implementation of class VolumeManager in volumes.py compared to novaclientv1.1 and does not have the list function.

**Comment by ibmcb** [comment]
Hello,

This was already fixed on the experimental branch. 
I intend to incorporate the changes on the experimental branch back into the master soon. Meanwhile, I recommend that you just try it out from experimental.

**Comment by ibmcb** [comment]
Already incorporated in the latest commit.
