### ISSUE TITLE
Scaling UP Error

### ISSUE THREAD

**Issue by rkarn** [ibmcb/cbtool#137]
I run the cbtool orchestrator node on AMAZON EC2. I am facing issue in scaling up the hadoop workload with airesize command. The issue persists with load profile of kmeans and terasort. I can scale down successfully.  The error details are below:

(MYAMAZON) airesize MYAMAZON ai_1 hadoopslave +1
ubuntu@ip-172-31-54-218: $ tail -f /var/log/cloudbench/root operations.log Jan 23 09:30:58 ip-172-31-54-218.ec2.internal
[2017-01-23 09:30:58,652] [DEBUG] process management.py/ProcessManagement.retriable run os command pro-
cess management - Command " /cb restart hadoop cluster.sh" failed to execute on hostname 172.31.57.69 after at-
tempt 1. Will try 2 more times. Jan 23 09:31:03 ip-172-31-54-218.ec2.internal [2017-01-23 09:31:03,840] [DEBUG]
process management.py/ProcessManagement.run os command process management - Error while executing the command
line " /cb restart hadoop cluster.sh" (returncode = 3700) :Warning: Permanently added '172.31.57.69' (ECDSA) to the list
of known hosts. bash: /home/cbuser/cb restart hadoop cluster.sh: No such le or directory Jan 23 09:31:03 ip-172-31-54-
218.ec2.internal [2017-01-23 09:31:03,840] [DEBUG] process management.py/ProcessManagement.retriable run os command
process management - Command " /cb restart hadoop cluster.sh" failed to execute on hostname 172.31.57.69 after attempt
2. Will try 1 more times.

**Comment by maugustosilva** [comment]
I have opened a new pull request (138) with a fix for the problem. While it is being reviewed, you can pull the latest fixes from the experimental branch.

**Comment by hinesmr** [comment]
@rkarn Is this fixed for you?

**Comment by maugustosilva** [comment]
Commit 6bc23dbd1f208ae4659b5d70ef1cae31f3381bcf supposedly fixes it. Feel free to re-open if needed.
