### ISSUE TITLE
Floating IPs not deleted after restart of cbtool with soft_reset

### ISSUE THREAD

**Issue by akrzos** [ibmcb/cbtool#140]
I have run speccloud using cbtool with floating ip addresses on OpenStack Ocata and found that my floating ip subnet was exhausted since after each run I would use `./cb --soft_reset` to clean up the instances, however the floating ips remained.  It would be nice if the floating ip addresses were deleted when the instances are deleted.

**Comment by maugustosilva** [comment]
Commit 6bc23dbd1f208ae4659b5d70ef1cae31f3381bcf supposedly fixes it. Feel free to re-open if needed.
