### ISSUE TITLE
Run the CloudBench orchestrator inside of the cloud

### ISSUE THREAD

**Issue by Second222None** [ibmcb/cbtool#144]
In order to run the cbtool, we need to have access to both the management network of the cloud and VMs inside the cloud. 
I installed the cbtool on a physical server that have access to management network of OpenStack. But I don't know how to connect to the VMs inside the cloud. 
I find a solution: Option 0: Sidestep the problem by running the CB Orchestrator directly in the Cloud. 
My Question: If we run the CB Orchestrator directly in the Cloud, how can we access the management network of OpenStack?

**Comment by maugustosilva** [comment]
Hello. Right, "Option 0" would require your CB Orchestrator instance to have outgoing access to external addresses, and the ability to reach out to OpenStack's API URLs. There are many setups that should allow this to happen: for instance, the CB Orchestrator could have two network interfaces, one a "provider network", with access to OpenStack API, and other on the "tenant network" used by the VMs.

**Comment by hinesmr** [comment]
@Second222None Closing this for now, as this is an OpenStack problem, rather than a cbtool problem. At the end of the day, you need to choose your own network. CloudBench supports multiple forms of network, but you'll have to decide for yourself what the initial requirements are.
