### ISSUE TITLE
Preparing Workload Images

### ISSUE THREAD

**Issue by Second222None** [ibmcb/cbtool#145]
Sorry to bother you! 
I have tested CBTOOL  against a "Simulated Cloud".  
Workload images are needed before test my OpenStack.
Is there any convenient way to get workload images?
If preparing images by myself, is there any special requirement about the version such as ycsb.
Hoping for your reply!!

**Comment by maugustosilva** [comment]
No bother at all. When you connect CBTOOL to your (non-Simulated) Cloud for the first time, you will see a prompt, instructing you on a step-by-step process (https://github.com/ibmcb/cbtool/wiki/HOWTO:-Preparing-a-VM-to-be-used-with-CBTOOL-on-a-real-cloud) on how to create a first workload image ("nullworkload"). You can later use the same technique to create images for other workloads (the automated installer already checks for correct versions on each package).

**Comment by Second222None** [comment]
When I follow the prompt (https://github.com/ibmcb/cbtool/wiki/HOWTO:-Preparing-a-VM-to-be-used-with-CBTOOL-on-a-real-cloud) to prepare my first workload image, I came across the following problem:

The failure reason is that the m1.tiny is too small,  how to customize the CBTOOL to use another flavor.

(MYOPENSTACK WALKTHROUGH) vmattach check:xenial0
 status: Starting instance "cb-ubuntu-MYOPENSTACK-vm1-check" on OpenStack Cloud, using the image "xenial0" (fa05a663-a892-4639-b27c-a1fd936ef331) and size "m1.tiny" (1), connected to network "demo-net", on VMC "RegionOne", under tenant "default", injecting the contents of the pub ssh key "ubuntu_cbtool_rsa" (userdata is "None").
 status: Waiting for vm_1 (B0C2B003-FDBB-5D0C-870C-7B9C6131D32B), to start...
 status: vm_1 (0c328a8c-75bd-41c7-aa77-9a6109823caf) could not be created on OpenStack Cloud "MYOPENSTACK" :  ERROR while checking for ACTIVE state (The VM creation will be rolled back)
VM object B0C2B003-FDBB-5D0C-870C-7B9C6131D32B (named "vm_1") could not be attached to this experiment: vm_1 (0c328a8c-75bd-41c7-aa77-9a6109823caf) could not be created on OpenStack Cloud "MYOPENSTACK" :  ERROR while checking for ACTIVE state (The VM creation will be rolled back)

**Comment by ibmcb** [comment]
Add the following contents to your cloud configuration file

```
[VM_TEMPLATES : OSK_CLOUDCONFIG]
CHECK = size:m1.large, imageid1:to_replace
```
This will override the default definition for this VM role (`check`) allowing you to deploy with a larger flavor. Please keep the value of the attribute `imageid` equals `to_replace` (this very literal string), and the re-execute CBTOOL (with  the option --soft_reset, to force a re-reading of your configuration file)

**Comment by hinesmr** [comment]
@Second222None CloudBench supports many different methods of generating images, both manual and automated. If one of them is still not working for you, please reopen the issue with specific error messages that you need help with.
