### ISSUE TITLE
VM OS resource usage collection

### ISSUE THREAD

**Issue by Second222None** [ibmcb/cbtool#147]
I was not able to extract VM OS metrics from VMs after setting [MON_DEFAULTS] COLLECT_FROM_GUEST = True.
The proble like this：
(MYOPENSTACK) monextract VM os
 status: No samples of runtime_os metrics for all VMs were found (the file /home/ubuntu/cbtool/lib/auxiliary//../../data/EXP-09-20-2017-01-22-42-AM-UTC/VM_runtime_os_EXP-09-20-2017-01-22-42-AM-UTC.csv will be empty).
Monitor extraction success. VM runtime OS performance data samples were written to the file /home/ubuntu/cbtool/lib/auxiliary//../../data/EXP-09-20-2017-01-22-42-AM-UTC/VM_runtime_os_EXP-09-20-2017-01-22-42-AM-UTC.csv.
Data is available at the url "rsync://192.168.100.6:873/ubuntu_cb/data/EXP-09-20-2017-01-22-42-AM-UTC".

How to enable the VM OS resource usage collection function?
Thank you!!!!

**Comment by Second222None** [comment]
Solved
My security group is not setup correctly.

**Comment by maugustosilva** [comment]
Great... closing it then. Thanks
