### ISSUE TITLE
Request: creation of an explicit "run in background" option for cbtool

### ISSUE THREAD

**Issue by morourke** [ibmcb/cbtool#160]
There are cases, such as software automation, where an explicit non-blocking way to start cbtool would be very helpful. I think the most direct approach would be a command line option, though a config file parameter could work as well.

Ideally there is also a way to query cbtool, while in the background, to: check if cbtool is properly connecting to the target cloud and to gracefully shutdown cbtool.

**Comment by maugustosilva** [comment]
Just properly documented the way to use CBTOOL in the background here: https://github.com/ibmcb/cbtool/wiki/FAQ-U#wiki-uq12
