### ISSUE TITLE
cinderclinet missing from docker image

### ISSUE THREAD

**Issue by jtaleric** [ibmcb/cbtool#161]
Playing with CBTool in a docker image, i saw : https://gist.github.com/jtaleric/50602710565c57b9ad05b46e8e06592a

To fix this, I simply issued a pip install python-cinderclient

Could this be missing from the docker install?

**Comment by maugustosilva** [comment]
Updated documentation to reflect the fact that one has to use the "build scripts", instead of using "docker build" directly. Already done in the `experimental` branch, waiting for PR review.
