### ISSUE TITLE
The SIM cloud  could not be attached to this experiment

### ISSUE THREAD

**Issue by gokhan27** [ibmcb/cbtool#264]
Hi,
I am trying to use cbtool and I followed https://github.com/ibmcb/cbtool/wiki/HOWTO:-Initial-Installation guide , but when I execute '~/cbtool/cb --soft_reset', it gives The SIM cloud named "MYSIMCLOUD" could not be attached to this experiment: 'str' object has no attribute 'iteritems'. How can I debug this problem and what can be the solution of this problem ? Maybe I am missing to do some things. The logs are belows:

ubuntu@cbimage:~$ ~/cbtool/cb --hard_reset
Cbtool version is "d477d6a"
Parsing "cloud definitions" file..... "/home/ubuntu/cbtool/lib/auxiliary//../..//configs/ubuntu_cloud_definitions.txt" opened and parsed successfully.

Checking "Object Store".....An Object Store of the kind "Redis" (shared) on node 10.0.0.25, TCP port 6379, database id "0" seems to be running.
Checking "Log Store".....A Log Store of the kind "rsyslog" (private) on node 10.0.0.25, UDP port 5114 seems to be running.
Checking "Metric Store".....A Metric Store of the kind "MongoDB" (shared) on node 10.0.0.25, TCP port 27017, database id "metrics" seems to be running.
Checking "File Store".....A File Store of the kind "rsync" (private) on node 10.0.0.25, TCP port 873 seems to be running.

Executing "hard" reset: (killing all running toolkit processes and flushing stores) before starting the experiment......
    Killing all processes... done
    Flushing Object Store... done
    Flushing Log Store... done
    Flushing Metric Store... done

Checking for a running API service daemon.....API Service daemon was successfully started. The process id is ['28860'] (http://10.0.0.25:7070).
Checking for a running GUI service daemon.....GUI Service daemon was successfully started. The process id is ['28884', '28885'], listening on port 8080. Full url is "http://10.0.0.25:8080".

 ############################# Executing command "cldattach sim MYSIMCLOUD" (specified on the configuration file) 

 status: Checking if the ssh key pair "ubuntu_cbtool_rsa" is created on VMC simzone_b....
 status: Checking if the security group "simsecgrp" is created on VMC simzone_b....
 status: Checking if the network "private" can be found on VMC simzone_b...
 status: Checking if the imageids associated to each "VM role" are registered on VMC "simzone_b"....
 status:  INFO    Image id for VM roles "oldisimlb,oldisimdriver,oldisimleaf,oldisimroot" is "960120F3-D6A3-5910-93B4-9D24F0BE9FAD" ("cb_oldisim") and it is already registered.
          INFO    Image id for VM roles "lb,tinyvm,yatinyvm" is "AE60094F-802B-531A-8EFB-CA5294990675" ("cb_nullworkload") and it is already registered.
          INFO    Image id for VM roles "driver_tradelite,client_tradelite" is "C5F67B76-920D-5102-A7F8-80F83657CB06" ("cb_tradelite") and it is already registered.
          INFO    Image id for VM roles "mongodb,ycsb,seed,cassandra,mongos,redis,mongo_cfg_server" is "F50D2E6B-8F80-5257-ADB0-C193BA618B1C" ("cb_ycsb") and it is already registered.
          INFO    Image id for VM roles "netserver,driver_netperf,netclient" is "38DC1010-76D8-5115-90D3-ED72E9C70E79" ("cb_netperf") and it is already registered.
          INFO    Image id for VM roles "apache,wrk" is "7FCE41A7-7A19-5927-A11E-1AB674F71E7A" ("cb_wrk") and it is already registered.
          INFO    Image id for VM roles "driver_coremark,coremark" is "B770C650-94D0-5192-93C2-E377A53139C3" ("cb_coremark") and it is already registered.
          INFO    Image id for VM roles "giraphpmaster,giraphslave" is "F3E4E17E-7D1B-5305-AB28-DE9E7AF404CF" ("cb_giraph") and it is already registered.
          INFO    Image id for VM roles "windows,client_windows" is "4322F915-BCBA-55FD-ADFE-A27D7FCC0D18" ("cb_windows") and it is already registered.
          INFO    Image id for VM roles "caffe" is "924E2A98-6949-573A-8E0B-849E6C0A12E2" ("cb_caffe") and it is already registered.
          INFO    Image id for VM roles "filebench,driver_filebench" is "91327B9B-AAED-5BD6-A67F-81E6A0304B32" ("cb_filebench") and it is already registered.
          INFO    Image id for VM roles "btest" is "C4BA42BC-BEF3-539F-AF98-D10D95204902" ("cb_btest") and it is already registered.
          INFO    Image id for VM roles "scimark" is "6234B55F-5B04-511E-95B4-D7E54A5FE69A" ("cb_scimark") and it is already registered.
          INFO    Image id for VM roles "xpingsender,xpingreceiver" is "D4A581AE-F8E1-53A9-8F57-4B438BC42AE7" ("cb_xping") and it is already registered.
          INFO    Image id for VM roles "postmark" is "58A980CA-77D5-53E7-9BD3-4F969435A479" ("cb_postmark") and it is already registered.
          INFO    Image id for VM roles "geronimo,mysql,client_open_daytrader" is "7FAD7B49-47BE-5A90-ABAC-7C13D31D0AE7" ("cb_open_daytrader") and it is already registered.
          INFO    Image id for VM roles "liberty,acmeair" is "338A3765-28E5-5CD6-8E38-A006F0026AF1" ("cb_acmeair") and it is already registered.
          INFO    Image id for VM roles "sysbench" is "25E5EA5D-08E4-5F33-987C-F427EFECFE7A" ("cb_sysbench") and it is already registered.
          INFO    Image id for VM roles "rubis_db,rubis,client_rubis" is "55771B7F-8839-58B6-B9FB-CBF02E890561" ("cb_rubis") and it is already registered.
          INFO    Image id for VM roles "client_ibm_daytrader,db2,driver_daytrader,was" is "8121A98C-3E2C-57FB-A300-2BDAFFAB23EB" ("cb_daytrader") and it is already registered.
          INFO    Image id for VM roles "specjbb" is "3AE78C3F-EF6A-51FC-8B84-128FAD0BBD12" ("cb_specjbb") and it is already registered.
          INFO    Image id for VM roles "iperfserver,iperfclient" is "D8D19E07-9C0E-51D1-8229-FD86D2C79D48" ("cb_iperf") and it is already registered.
          INFO    Image id for VM roles "willfail" is "C8B57F26-2AE8-557B-8C5E-F0C2B3D69035" ("doesnotmatter") and it is already registered.
          INFO    Image id for VM roles "cn_hpc,fen_hpc" is "E6430504-5399-5196-9713-9204C16D3476" ("cb_hpcc") and it is already registered.
          INFO    Image id for VM roles "parboil" is "86EE5102-EEC0-5FDE-9C9A-1AB2E0829AF4" ("cb_parboil") and it is already registered.
          INFO    Image id for VM roles "ddgen" is "0FA56845-48B4-5A58-BA0B-BA96A1DAF785" ("cb_ddgen") and it is already registered.
          INFO    Image id for VM roles "rubbos,client_rubbos" is "35A1CF18-8B69-54BC-9171-5C4391892CC2" ("cb_rubbos") and it is already registered.
          INFO    Image id for VM roles "driver_hadoop,hadoopmaster,hadoopslave" is "CBAAD8F2-7FBE-5C46-8389-0129E31BF4D9" ("cb_hadoop") and it is already registered.
          INFO    Image id for VM roles "linpack" is "1102D5FD-B51A-5ED0-B0C7-D55BC1B00456" ("cb_linpack") and it is already registered.
          INFO    Image id for VM roles "multichase" is "57BF7551-8EA8-5DAB-BA86-36E295427BC5" ("cb_multichase") and it is already registered.
          INFO    Image id for VM roles "nuttcpserver,nuttcpclient" is "ED1079FF-3A71-5F38-A14F-14BF1DF45E9F" ("cb_nuttcp") and it is already registered.
          INFO    Image id for VM roles "memtier" is "CB308AB7-627B-5A11-A26C-17C08E5ADD96" ("cb_memtier") and it is already registered.
          INFO    Image id for VM roles "bonnie" is "4FCAC58B-2F55-5149-88CA-99F61CC7D856" ("cb_bonnie") and it is already registered.
          INFO    Image id for VM roles "predictablevm,faildb2" is "77A8FB76-F3E8-56E2-BA27-6C2907F59B80" ("cloudbench_root") and it is already registered.
          INFO    Image id for VM roles "fio,driver_fio,unixbench" is "7B1C177F-2425-501A-BA4B-99AA94FADD15" ("cb_fio") and it is already registered
 status: VMC "simzone_b" was successfully tested.

 status: Checking if the ssh key pair "ubuntu_cbtool_rsa" is created on VMC simzone_a....
 status: Checking if the security group "simsecgrp" is created on VMC simzone_a....
 status: Checking if the network "private" can be found on VMC simzone_a...
 status: Checking if the imageids associated to each "VM role" are registered on VMC "simzone_a"....
 status:  INFO    Image id for VM roles "oldisimlb,oldisimdriver,oldisimleaf,oldisimroot" is "960120F3-D6A3-5910-93B4-9D24F0BE9FAD" and it is already registered.
          INFO    Image id for VM roles "lb,tinyvm,yatinyvm" is "AE60094F-802B-531A-8EFB-CA5294990675" and it is already registered.
          INFO    Image id for VM roles "driver_tradelite,client_tradelite" is "C5F67B76-920D-5102-A7F8-80F83657CB06" and it is already registered.
          INFO    Image id for VM roles "mongodb,ycsb,seed,cassandra,mongos,redis,mongo_cfg_server" is "F50D2E6B-8F80-5257-ADB0-C193BA618B1C" and it is already registered.
          INFO    Image id for VM roles "netserver,driver_netperf,netclient" is "38DC1010-76D8-5115-90D3-ED72E9C70E79" and it is already registered.
          INFO    Image id for VM roles "apache,wrk" is "7FCE41A7-7A19-5927-A11E-1AB674F71E7A" and it is already registered.
          INFO    Image id for VM roles "driver_coremark,coremark" is "B770C650-94D0-5192-93C2-E377A53139C3" and it is already registered.
          INFO    Image id for VM roles "giraphpmaster,giraphslave" is "F3E4E17E-7D1B-5305-AB28-DE9E7AF404CF" and it is already registered.
          INFO    Image id for VM roles "windows,client_windows" is "4322F915-BCBA-55FD-ADFE-A27D7FCC0D18" and it is already registered.
          INFO    Image id for VM roles "caffe" is "924E2A98-6949-573A-8E0B-849E6C0A12E2" and it is already registered.
          INFO    Image id for VM roles "filebench,driver_filebench" is "91327B9B-AAED-5BD6-A67F-81E6A0304B32" and it is already registered.
          INFO    Image id for VM roles "btest" is "C4BA42BC-BEF3-539F-AF98-D10D95204902" and it is already registered.
          INFO    Image id for VM roles "scimark" is "6234B55F-5B04-511E-95B4-D7E54A5FE69A" and it is already registered.
          INFO    Image id for VM roles "xpingsender,xpingreceiver" is "D4A581AE-F8E1-53A9-8F57-4B438BC42AE7" and it is already registered.
          INFO    Image id for VM roles "postmark" is "58A980CA-77D5-53E7-9BD3-4F969435A479" and it is already registered.
          INFO    Image id for VM roles "geronimo,mysql,client_open_daytrader" is "7FAD7B49-47BE-5A90-ABAC-7C13D31D0AE7" and it is already registered.
          INFO    Image id for VM roles "liberty,acmeair" is "338A3765-28E5-5CD6-8E38-A006F0026AF1" and it is already registered.
          INFO    Image id for VM roles "sysbench" is "25E5EA5D-08E4-5F33-987C-F427EFECFE7A" and it is already registered.
          INFO    Image id for VM roles "rubis_db,rubis,client_rubis" is "55771B7F-8839-58B6-B9FB-CBF02E890561" and it is already registered.
          INFO    Image id for VM roles "client_ibm_daytrader,db2,driver_daytrader,was" is "8121A98C-3E2C-57FB-A300-2BDAFFAB23EB" and it is already registered.
          INFO    Image id for VM roles "specjbb" is "3AE78C3F-EF6A-51FC-8B84-128FAD0BBD12" and it is already registered.
          INFO    Image id for VM roles "iperfserver,iperfclient" is "D8D19E07-9C0E-51D1-8229-FD86D2C79D48" and it is already registered.
          INFO    Image id for VM roles "willfail" is "C8B57F26-2AE8-557B-8C5E-F0C2B3D69035" and it is already registered.
          INFO    Image id for VM roles "cn_hpc,fen_hpc" is "E6430504-5399-5196-9713-9204C16D3476" and it is already registered.
          INFO    Image id for VM roles "parboil" is "86EE5102-EEC0-5FDE-9C9A-1AB2E0829AF4" and it is already registered.
          INFO    Image id for VM roles "ddgen" is "0FA56845-48B4-5A58-BA0B-BA96A1DAF785" and it is already registered.
          INFO    Image id for VM roles "rubbos,client_rubbos" is "35A1CF18-8B69-54BC-9171-5C4391892CC2" and it is already registered.
          INFO    Image id for VM roles "driver_hadoop,hadoopmaster,hadoopslave" is "CBAAD8F2-7FBE-5C46-8389-0129E31BF4D9" and it is already registered.
          INFO    Image id for VM roles "linpack" is "1102D5FD-B51A-5ED0-B0C7-D55BC1B00456" and it is already registered.
          INFO    Image id for VM roles "multichase" is "57BF7551-8EA8-5DAB-BA86-36E295427BC5" and it is already registered.
          INFO    Image id for VM roles "nuttcpserver,nuttcpclient" is "ED1079FF-3A71-5F38-A14F-14BF1DF45E9F" and it is already registered.
          INFO    Image id for VM roles "memtier" is "CB308AB7-627B-5A11-A26C-17C08E5ADD96" and it is already registered.
          INFO    Image id for VM roles "bonnie" is "4FCAC58B-2F55-5149-88CA-99F61CC7D856" and it is already registered.
          INFO    Image id for VM roles "predictablevm,faildb2" is "77A8FB76-F3E8-56E2-BA27-6C2907F59B80" and it is already registered.
          INFO    Image id for VM roles "fio,driver_fio,unixbench" is "7B1C177F-2425-501A-BA4B-99AA94FADD15" and it is already registered
 status: VMC "simzone_a" was successfully tested.

The SIM cloud named "MYSIMCLOUD" could not be attached to this experiment: 'str' object has no attribute 'iteritems'

 ############################# Executing command "vmcattach all" (specified on the configuration file) 

Usage: vmcattach <cloud_name> <identifier> [temp_attr_list = empty=empty] [mode] 
()

**Comment by maugustosilva** [comment]
This has been solved in commit `2a4021334d02d81d342fd259a05dde6b57146543`. For already installed CB orchestrators, just execute `sudo pip install redis==2.10.6` and try again.

**Comment by gokhan27** [comment]
thanks maugustosilva, it is now working.
