### ISSUE TITLE
How to create ubuntu 16.04 LTS YCSB Benchmark Image

### ISSUE THREAD

**Issue by gokhan27** [ibmcb/cbtool#289]
I am trying to create ycsb image with 'vmattach check:cb_nullworkload:ubuntu:ycsb' command on my OpenStack environment. But it gives 'VM object 74BF6DFF-3541-5672-ACDB-5B837AE58CAE (named "vm_1") could not be attached to this experiment: VM object initialization failure: 'ycsb' '.  Maybe I am missing something. is there any way to create ycsb image ?
ı also created cassandra_ycsb image but when I try  aiattach command It gives "image not found error". Can you help me for these problems ?

**Comment by hinesmr** [comment]
@maugustosilva Wanna tackle that one?
