### ISSUE TITLE
Kubernetes - problems to deploy cassandra_ycsb workload

### ISSUE THREAD

**Issue by pawelzell** [ibmcb/cbtool#355]
I want to benchmark a Kubernetes cluster using CBTOOL. I followed the user guide, manage to deploy nullworkload and capture metrics from the task. When I try to execute aiattach with workload being cassandra_ycsb, hadoop or sysbench command fails.

First, I want to make cassandra_ycsb work. When I execute `aiattach cassandra_ycsb`, I am getting error:

`Parallel run os command operation failure: Giving up on executing command "~/cb_restart_seed.sh" on hostname 172.17.0.3. Too many attempts (3).`

When I check /var/log/XXXX_remotescripts.log it looks like logs from the failing step are:

```
Nov 19 09:20:51 cb-root-mykub-vm1-seed-ai-1_10-244-1-4 cloudbench EXP-11-19-2019-08-05-27-AM-UTC cb_common.sh (6475): Obtaining the node list for this Cassandra cluster by running "nodetool -u cassandra -pw cassandra -h 10.244.1.4 status"...
Nov 19 09:20:53 cb-root-mykub-vm1-seed-ai-1_10-244-1-4 cloudbench EXP-11-19-2019-08-05-27-AM-UTC cb_common.sh (6475): Nodes registered on the cluster: 0 out of 2
Nov 19 09:20:53 cb-root-mykub-vm1-seed-ai-1_10-244-1-4 cloudbench EXP-11-19-2019-08-05-27-AM-UTC cb_common.sh (6475): Make sure that Keyspace "system" is present
```

The image of ycsb I am using came from ibmcb Docker hub. The cluster I am using is set up using https://kind.sigs.k8s.io/ so each Kubernetes node is a Docker container.

Does somebody ran CBTOOL with Kubernetes recently and was able to make it work?

**Comment by maugustosilva** [comment]
Apologies for the late reply. I was traveling, and I am back in the country today. 

Will take a look on the image from DockerHub, trying to reproduce your error. If reproduction positive, will update the image there before the end of the week.

Meanwhile, you can try to rebuild the image with the (admittedly, highly experimental) tooling at https://github.com/ibmcb/cbtool/wiki/HOWTO:-Creating-images-for-additional-Virtual-Application-types

**Comment by pawelzell** [comment]
Any progress on reproducing the error? If the image works for you, could you send me your configuration file and tell me on what type of Kubernetes cluster have you run it?

FYI: most of the workloads from docker hub works on my cluster, but a few more advanced like ycsb_cassandra, hadoop, sysbench does not.

**Comment by mraygalaxy** [comment]
@pawelzell OK, so I've done this quite a bit, actually. The problem we have in k8s is the way networking is handled. Can you present a more detailed view of your k8s networking setup? I've made some changes to CB recently that make this more amenable. We have two solutions:

1. CB is on the same network as k8s (you need to make sure all of CB's services are reachable by k8s containers)
2. CB is not on the same network as k8s => We have OpenVPN support to work around this.

**Comment by pawelzell** [comment]
@mraygalaxy thank you for your reply. Some time after posting I moved from running k8s locally in kind (Kubernetes in docker) in favour of setting up on bare metal machines. This probably fixed the issue, the described problem with the image no longer persists.
