### ISSUE TITLE
python2 deps refinement for install

### ISSUE THREAD

**Issue by stdweird** [ibmcb/cbtool#382]
when running `~/cbtool/install -r orchestrator` some python2 dependencies need to be added/refined as lots of things move to py3 only versions. 

i ended up doing (before the install)
```
sudo yum -y install epel-release git


sudo yum install -y python2-pip
sudo pip install --upgrade pip
sudo pip install wheel

sudo pip install monotonic 
sudo pip install 'zipp<2.0'
sudo pip install 'apache-libcloud<3.0'
sudo pip install 'six>=1.11.0'

```

in a bare centos78 vm. 

the last 3 are the deps that need to be refined/added.
updating pip and installing wheel are nice to haves. (pip might be restricted to 'pip<21')

the install script also check for a strange/old version of pip, resulting in
```
[INFO] dependencies.py/execute_command  - (9) RESULT for command "pip --version | cut -d ' ' -f 2;" :  NOT OK. Version mismatch (wanted: 1.5.4, provided: ) CORRECTIVE ACTION:  Please install/configure "pip" by issuing the following command: "sudo yum -y install  epel-release;sudo yum -y install   python-pip;"
```
not sure why anyone wants that specific version, but after upgrading pip, checking for pip 20 is ok. (centos 78  / epel ships 8.1)

**Comment by stdweird** [comment]
for the bare VM, there was another problem: it had cloud-init, and that pulled in PyYAML 3.10, python-ipaddress 1.0.14 and python-requests 2.6.0 as rpm dep. however, there is a PyYAML dep for 3.12, ipaddress for 1.0.17 and requests dep for 2.20.0, so following hackery is needed in this case
```
sudo rpm -e PyYAML python-requests python-ipaddress --nodeps
sudo pip install 'PyYAML==3.12'
sudo pip install 'requests==2.20.0'
sudo pip install 'ipaddress==1.0.17'
```
(i kept the pip version as close as possible to the rpm installed one)

**Comment by stdweird** [comment]
more things: on centos7, default mongodb that gets installed is 2.6 which ships broken config file, i did following to get mongo (before running the install)
```
sudo wget https://repo.mongodb.org/yum/redhat/mongodb-org-3.1.repo -O /etc/yum.repos.d/mongo.repo
sudo sed -i 's/3.1/3.2/' /etc/yum.repos.d/mongo.repo
sudo yum install -y mongodb-org mongodb-org-server
sudo sed -i '/.*bindIp/d' /etc/mongod.conf
```

**Comment by maugustosilva** [comment]
Hi @stdweird... many thanks for the identified issues. As you have guessed at this point, we are not actively developing/testing directly on CentOS, and that is why some of these fall under our radar. From my standpoint, the problems you have identified are legitimate ones, and we would welcome a PR to fix these (the changes are basically concentrated on https://github.com/ibmcb/cbtool/blob/master/docker/orchestrator/Dockerfile-centos_cb_orchestrator)

**Comment by stdweird** [comment]
@maugustosilva ok, i'll see what i can come up with. i'm now working in my own branch https://github.com/stdweird/cbtool/tree/centos7 and have found some other bugs too, as you can see from the commits.

**Comment by mraygalaxy** [comment]
We've also made some first steps to get a port to python3. It's early stages, but it's coming along.

**Comment by maugustosilva** [comment]
Hey @stdweird just letting you know that we merged the python3 support back into master.

**Comment by mraygalaxy** [comment]
Closing this one as python3 support is now merged.
