### ISSUE TITLE
generated gmond configuration file incorrect

### ISSUE THREAD

**Issue by cpschult** [ibmcb/cbtool#57]
In my (limited) testing I have found cbtool only reports VM utilization data for one VM in each AI.  I've been testing with AI cassandra_ycsb with 1 ycsb, 1 seed and 1 cassandra node.  Only the ycsb node was reporting CPU usage, etc, on the CB GUI.

Upon further inspection, there are appear to be two problems in  cb_create_gmond_config_file.sh:
1) Retrieving the COLLECTOR_UNICAST_IP should not specify ${my_ai_uuid} as a paramter to get_my_ai_attribute_with_default on line 26.  
For example:
```
cbuser@cb-root-csfsm2pvc-vm27-cassandra:~$ get_my_ai_attribute_with_default ${my_ai_uuid} metric_aggregator_ip none
metric_aggregator_ip
cbuser@cb-root-csfsm2pvc-vm27-cassandra:~$ get_my_ai_attribute_with_default metric_aggregator_ip none
192.168.148.43
cbuser@cb-root-csfsm2pvc-vm27-cassandra:~$
```

Removing `${my_ai_uuid}` allows the script to pick up the real metric_aggregator_ip.

2) If I understand correctly one VM in an AI should run gmetad to collect gmond data from the other VMs in that deployed AI.
In my testing the ycsb node was starting gmetad and gmond.  ( good )
The seed and cassandra nodes only started gmond. ( again, I think that is correct)

The problem on the cassandra and seed node is in the generated gmond configuration (gmond-vms.conf);  COLLECTOR_UNICAST_IP is set to an IP address local to the VM ( instead of the ycsb node where gmetad is running).

I think this section of code at the top of cb_create_gmond_config_file.sh is the culprit.  This code will always set the COLLECTOR_UNICAST_IP to the my_ip_addr.  ( Except on the ycsb node where grep in the conditional returns 1 and my_ip_addr is already equal to metric_aggregator_ip ( and COLLECT_UNICAST_IP ) )
```
if [[ $(sudo ifconfig -a | grep -c $COLLECTOR_UNICAST_IP) -eq 0 ]]
then
       COLLECTOR_UNICAST_IP=${my_ip_addr}
fi
```
I commented out the conditional block and now the seed and cassandra generated gmond configurations files that point at gmetad on the ycsb node.  Ultimately the gmond from all AI VMs is reported back to cbtool (and the CB GUI ).

**Comment by cpschult** [comment]
Providing a diff of code I've used successfully. ( same as described above )

```
diff --git a/scripts/common/cb_create_gmond_config_file.sh b/scripts/common/cb_create_gmond_config_file.sh
index e3a7cd7..dcca1c6 100755
--- a/scripts/common/cb_create_gmond_config_file.sh
+++ b/scripts/common/cb_create_gmond_config_file.sh
@@ -23,15 +23,19 @@ GMOND_VMS=~/gmond-vms.conf
 python_module_path=~/util/python_ganglia_modules
 python_modules=~/util/ganglia_conf.d

-COLLECTOR_UNICAST_IP=`get_my_ai_attribute_with_default ${my_ai_uuid} metric_aggregator_ip none`
+COLLECTOR_UNICAST_IP=`get_my_ai_attribute_with_default metric_aggregator_ip none`
 COLLECTOR_MULTICAST_IP=`get_global_sub_attribute mon_defaults collector_multicast_ip`
 COLLECTOR_MULTICAST_PORT=`get_global_sub_attribute mon_defaults collector_vm_multicast_port`
 COLLECTOR_VM_PORT=`get_global_sub_attribute mon_defaults collector_vm_port`

-if [[ $(sudo ifconfig -a | grep -c $COLLECTOR_UNICAST_IP) -eq 0 ]]
-then
-       COLLECTOR_UNICAST_IP=${my_ip_addr}
-fi

 cat << EOF > $GMOND_VMS
 globals {

```

**Comment by maugustosilva** [comment]
Commit id 6d2c3a0eea348ffb2800cf4e1e82aa0eeea99204 fixed the issue. Thanks Chris!
