### ISSUE TITLE
Cassandra nodes can't join cluster concurrently

### ISSUE THREAD

**Issue by cpschult** [ibmcb/cbtool#59]
I have started testing with 6 node cassandra clusters and have hit the problem described below.  Typically 1 or 2 nodes in the AI fail to join the cassandra cluster because of the error.  

I am trying to add a delay in the initialization on each 'cassandra' node but don't have code that fixes the problem yet.  If I find a solution I will share it.

The cassandra change is fairly new and appears to have been integrated to cassandra in Sep. 2014 [1].  

Error Information logged to /var/log/cassandra/system.log on deployed VM:
```
ERROR [main] 2015-01-16 14:19:36,301 CassandraDaemon.java:465 - Exception encountered during startup
java.lang.UnsupportedOperationException: Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while cassandra.consistent.rangemovement is true
        at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:797) ~[apache-cassandra-2.1.2.jar:2.1.2]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:652) ~[apache-cassandra-2.1.2.jar:2.1.2]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:535) ~[apache-cassandra-2.1.2.jar:2.1.2]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:324) [apache-cassandra-2.1.2.jar:2.1.2]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:448) [apache-cassandra-2.1.2.jar:2.1.2]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:537) [apache-cassandra-2.1.2.jar:2.1.2]
```

Cisco uses cassandra in one of its products and provides this guidance.  They recommend two MINUTES between adding nodes.  
http://www.cisco.com/c/en/us/td/docs/video/videoscape/cloud_object_store/2-1-1/release-notes/COS_RelNotes_2_1_1.html
```
CSCur99109	Bootstrapping issue when starting up the Cassandra service.
	When two or more nodes are added to a cluster in quick succession, an issue may arise in which the Cassandra service fails to initialize on the new node, preventing it from being added to the Cassandra cluster.
	This failure is indicated by the following error message in the Cassandra event log (/var/log/cassandra/cassandra.log):
	Exception encountered during startup: Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while cassandra.consistent.rangemovement is true. 
	  
	The root cause of this issue is that the node is being added while the Cassandra cluster topology is still in flux, so that initialization of the new node cannot proceed.
	To avoid this possible issue, be sure to provide (or have a script provide) a time delay of at least two minutes between adding two nodes to the cluster in sequence.
```

[1]  http://mail-archives.apache.org/mod_mbox/cassandra-commits/201409.mbox/%3Cd903ee96afbc4d83bae0b10214276260@git.apache.org%3E

**Comment by cpschult** [comment]
It seems possible to work around this problem by leaving only one node as a non-seed node.  For example,
typealter cassandra_ycsb sut=ycsb->5_x_seed->1_x_cassandra

As YCSB uses the list of cassandra seed IPs as the hosts to test against.  This change has a side affect of driving YCSB traffic to 5 nodes instead of 3 ( the default configuration appears to be 'ycsb->3_x_seed->3_x_cassandra' )

**Comment by ibmcb** [comment]
Thanks Chris. The default configuration for the workload at the moment is ycsb->1_x_seed->1_x_cassandra, and there is recommendation to never deploy with more than one data node.
