### ISSUE TITLE
EC2 volume deletion

### ISSUE THREAD

**Issue by bowers** [ibmcb/cbtool#62]
When running with EBS-backed instances on EC2, when I detach a VM I get an error related to deleting the volume:
 
ec2_cloud_ops.py/Ec2Cmds.vmdestroy TEST_user - VM XXX could not be destroyed  on Elastic Compute Cloud "EC2CLOUD" : Volume previously attached to
the vm_3 (cloud-assigned uuid i-xxxxxxxx) could not be destroyed  on Elastic Compute Cloud "EC2CLOUD" : local variable '_volume' referenced before assignment

ec2_cloud_ops.py code includes a comment that implies there's a known issue around deleting volumes.  

I'm working around the issue by commenting out the _volume.delete() line in vvdestroy(), and by commenting out the line unattachedvol.delete() in vmdestroy().

**Comment by ibmcb** [comment]
This has been fixed in the most recent commit. Feel free to re-open if needed.
