### ISSUE TITLE
monextract for vm_runtime_os data fails on key time_cbtool and time_cbtool_t

### ISSUE THREAD

**Issue by cpschult** [ibmcb/cbtool#77]
I was not able to extract VM_RUNTIME_OS data from VMs after setting mon_defaults.collect_from_guest to True.
 
Running monextract manually returned an error:
(PVC2A) monextract PVC2A VM os
Monitor extraction failure: 'time_cbtool'
 
It appears the default vm_rumtime_os_metrics_header value includes 'time_cbtool' and 'time_cbtool_h'.  Neither of those values are present in the runtime_os data. ( confirmed by looking at data in mongo )
 
I removed those two metrics from the mon_default value for key vm_rumtime_os_metrics and successfully extract the VM OS data (CPU,MEM, etc.).
 
I can see where 'time_cbtool' is generated when load managers report their application results.  ( scripts/common/cb_common.py.report_app_metrics() )  But I don't see a routine to report OS metrics in that file.

Recommended fixes:
-- Remove time_cbtool and time_cbtool_h from the list of default columns to extract for vm_runtime_os data. (Looks like they may have been added through the use of TSTAMP value in REPORTED_RUNTIME_OS_VM_METRIC_NAMES.  configs/templates/internal_options.txt )
-- Add time_cbtool and time_cbtool_h to vm_rumtime_os data generation. ( in gmetad.py? )

**Comment by ibmcb** [comment]
I believe this has been fixed in most recent commits. Will close for now, feel free to re-open.
