### ISSUE TITLE
cbtool support for cassandra 2.2.x?

### ISSUE THREAD

**Issue by cpschult** [ibmcb/cbtool#78]
Is there a plan in place for cbtool to support cassandra 2.2.x?  In my initial testing with cassandra 2.2.1 I've found two problems that prevent cbtool from interacting with cassandra 2.2.x.

1) cassandra-cli was deprecated in cassandra 2.1 and removed in cassandra 2.2.  ( contrary to their guidance which claimed it would not be removed until 3.0 [1] )  The alternative is to use cqlsh which appears to be a drop-in replacement for cassandra-cli.  I'll try a test soon to confirm.

2) Cassandra 2.2.x appears to disable remote JMX by default.  cbtool currently relies on remote JMX access to determine the cluster status. I've changed the configuration in cassandra-env.sh to allow remote JMX and disable authentication to work around this problem.  cbtool may need to perform this configuration automatically 

[1] http://wiki.apache.org/cassandra/CassandraCli

**Comment by cpschult** [comment]
I also set 'start_rpc' to true in the cassandra.yml configuration file.  I believe that is required for nodetool.

**Comment by hinesmr** [comment]
I fixed it. Re-pull cloudbench.

**Comment by ibmcb** [comment]
In addition to Michael's work, the commit https://github.com/ibmcb/cbtool/commit/57c1ff78044b4c06ccd1a7eab627773648dfcbc4 has code that works with both new (2.2+) and older (2.1-) Cassandras, provided that one has YCSB 0.50 or newer.
