### ISSUE TITLE
vCloud Director (VCD) and mongo password authentication 

### ISSUE THREAD

**Issue by bowers** [ibmcb/cbtool#82]
When using the vCloud Director driver, cb attempts to connect to the mongo metrics datastore using the password used to connect to the vCloud Director API.

I think this is due to poor naming for the VMC_DEFAULTS and VM_DEFAULTS parameters in the vCloud Director template (configs/templates/_vcd.txt).   Both sections have a parameter named simply PASSWORD.  The same parameter name is used as the optional password parameter in stores.txt.   The default value for PASSWORD in stores.txt ("$False") is likely being replaced by the value in _vcd.txt.

A work around until I fix the VCD code is to set a password for the mongo user to the same value as your VCD API password.

**Comment by hinesmr** [comment]
VCloud's use of liblcoud is not stable at all. I recommend examining the DigitalOcean and backporting whatever changes you need to make it so --- I've run the whole SPEC kit against digitalocean successfully now using the libcloud adapter.

**Comment by ibmcb** [comment]
I have updated the "Supported Clouds" table to at least make clear which adapters are (and are not) properly maintained. Will close it for now, feel free to re-open.
