### ISSUE TITLE
cbtool <-> PerfKitBenchmarker (PKB)

### ISSUE THREAD

**Issue by voellm** [ibmcb/cbtool#85]
A contributor to the PerfKitBenchmarker community recently pointed (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/606) out this project and asked how it is different from PKB.  If you are open to discussion I'd love to chat.

You are welcome to checkout how PKB and the community has evolved by checking out the community slides on the Wiki - https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki

Feel free to ping me at voellm@google.com

Thanks!

**Comment by hinesmr** [comment]
@voellm Cloudbench is 4 years old and not at all stale. We have a mailing list and active contributors as well as a set of fully documented wiki pages. I recommend you start there.

**Comment by hinesmr** [comment]
@maugustosilva looks like this can be closed.
