### ISSUE TITLE
Jump-box FIP attach failure

### ISSUE THREAD

**Issue by jtaleric** [ibmcb/cbtool#97]
Apr 19 16:32:39 host.com [2016-04-19 16:32:39,845] [WARNING] osk_cloud_ops.py/OskCmds.floating_ip_attach TEST_stack - (While getting instance(s) through API call "floating ip attach") Invalid input for field/attribute address. Value: False. False is valid under each of {'format': 'ipv6'}, {'format': 'ipv4'} (HTTP 400) (Request-ID: req-b726f240-2051-4297-ab7d-e5a907401778)

**Comment by ibmcb** [comment]
This is fixed on the experimental branch. Will be merged back into master soon.
